---
defaults:
  - _self_
  - features_config.yaml
  - model_config.yaml
  - training_config.yaml

# Hydra specific
# TODO: Add help message
hydra:
  help:
    template:
      'TODO: Add help message'

# Logging settings
log_level: DEBUG
tf_log_level: 1

# Run mode
run_mode: train
use_gpu: True

# glob-able paths to input files
TauFiles: "/home/bewilson/split_NTuples/*Gammatautau*/*.root"
FakeFiles: "/home/bewilson/split_NTuples/*JZ*/*.root"