---
defaults:
  - _self_
  - features_config.yaml
  - model_config.yaml
  - training_config.yaml
  - testing_config.yaml

# Hydra specific
# TODO: Add help message
hydra:
  help:
    template:
      'TODO: Add help message'
  run:
    dir:
      outputs/${run_mode}_output/${now:%Y-%m-%d_%H-%M-%S}

# Logging settings
log_level: DEBUG
tf_log_level: 1

# Run mode
run_mode: train
use_gpu: True
step_size: 5 GB 

# glob-able paths to input files
TauFiles: /home/bewilson/split_NTuples/*Gammatautau*/*.root
FakeFiles: /home/bewilson/split_NTuples/*JZ*/*.root

# Cuts
cuts: (TauJets_ptJetSeed > 15000) && abs(TauJets_etaJetSeed) < 2.5