---
defaults:
  - _self_
  - features_config.yaml
  - model_config.yaml
  - training_config.yaml
  - testing_config.yaml

# Hydra specific
# TODO: Add help message
hydra:
  help:
    template:
      'TODO: Add help message'
  run:
    dir:
      outputs/${run}_output/${now:%Y-%m-%d_%H-%M-%S}

# Logging settings
# TODO: actually implement this
log_level: DEBUG
tf_log_level: '1'

# Run mode
run: train
use_gpu: True
allow_gpu_growth: 'true'
step_size: 5 GB  # sets memory used by dataloaders

# glob-able paths to input files
TauFiles:  /hepgpu5-data3/benwilson/split_NTuples/*Gammatautau*/*.root
FakeFiles: /hepgpu5-data3/benwilson/split_NTuples/*JZ*/*.root

# Cuts
global_cuts: (TauJets_ptJetSeed > 15000) & (abs(TauJets_etaJetSeed) < 2.5)
tau_cuts: (${global_cuts} & ((TauJets_IsTruthMatched) & (abs(TauJets_truthEtaVis) < 2.5) & (TauJets_truthPtVis > 15000))) # & (TauJets_truthParticleType == 10) 
# TODO: Add truth particle type to NTuples in THOR
fake_cuts: ${global_cuts}
