---

# glob-able paths to input files
TauFiles: "/home/bewilson/split_NTuples/*Gammatautau*/*.root"
FakeFiles: "/home/bewilson/split_NTuples/*JZ*/*.root"

# Test/Train/Val split params
TestSplit: 0.2
ValSplit: 0.2
RandomSeed: 42