---
# @package _group_
model_name: DSNN
batch_norm: True
mask_value: -999
activation: swish

# Regularization
l1_penalty: 0.01
l2_penalty: 0.01
dropout: 0.1
regularization: 'l1l2'


# For TDD (Phi)
n_inputs:
  TauTracks: [64, 64, 64]
  NeutralPFO: [64, 64, 64]
  ShotPFO: [64, 64, 64]
  ConvTrack: [64, 64, 64]

# for Dense (F)
n_hiddens:
  TauTracks: [64, 64, 64]
  NeutralPFO: [64, 64, 64]
  ShotPFO: [64, 64, 64]
  ConvTrack: [64, 64, 64]
  TauJets: [64, 64, 64]

# For fully connected merged layers
n_dense_merged: [64, 32]
n_classes: 6
