---
# @package _group_
model_name: DSNN
batch_norm: True
mask_value: -999
dropout: 0.0

# For TDD (Phi)
n_inputs:
  TauTracks: [30,30,20]
  NeutralPFO: [80,80,60,60]
  ShotPFO: [20,20,20]
  ConvTrack: [30,30,20]

# for Dense (F)
n_hiddens:
  TauTracks: [20,20,20]
  NeutralPFO: [60,40,40]
  ShotPFO: [20,20,20]
  ConvTrack: [20,20,20]
  TauJets: [20, 20, 20]

# For fully connected merged layers
n_dense_merged: [100, 50]
n_fc1: 100
n_fc2: 50
n_classes: 6
