---
# @package _group_

# TauID working point effs
working_points: [95, 75, 60]

rejection_working_points: [95, 75, 60]

# Branches for outfile: i.e. network scores and key features for perf plots
OutFileBranches:
  - TauClassifier_Labels
  - TauJets_truthDecayMode
  - TauJets_IsTruthMatched
  - TauJets_truthEtaVis
  - TauJets_truthPtVis
  - TauJets_truthProng
  - TauClassifier_pTReweight
  - TauJets_mu
  - TauJets_ptJetSeed
  - TauJets_etaJetSeed
  - TauJets_phiJetSeed
  - TauJets_RNNJetScoreSigTrans
  - TauJets_is1p0n
  - TauJets_is1p1n
  - TauJets_is1pxn
  - TauJets_is3p0n
  - TauJets_is3pxn
  - TauJets_mcEventWeight


# Result Loader configs
visualiser:
  TauIDRNN:
    y_true: TauClassifier_isTrueTau
    y_pred: TauJets_RNNJetScoreSigTrans
    weights: TauClassifier_pTReweight
  
  UTC:
    y_true: TauClassifier_Labels
    y_pred: TauClassifier_Scores
    weights: TauClassifier_pTReweight

  UTC_TauID:
    y_true: TauClassifier_isTrueTau
    y_pred: TauClassifier_isTau
    weights: TauClassifier_pTReweight

sculpting_plots:
  TauJets_mu:
    x_scale: linear
    y_scale: linear
    units: ''
    bins: 25
  TauJets_ptJetSeed:
    x_scale: log
    y_scale: linear
    units: '[MeV]'
    bins: 25
  TauJets_etaJetSeed:
    x_scale: linear
    y_scale: linear
    units: ''
    bins: 25
  TauJets_phiJetSeed:
    x_scale: linear
    y_scale: linear
    units: ''
    bins: 25
  
