---

# Some aliases for branch names
truth_labels: TauClassifier_Labels
pred_labels: TauClassifier_Scores
weights: - TauClassifier_pTReweight

# TauID working point effs
wps: [95, 75, 60]

# Branches for outfile: i.e. network scores and key features for perf plots
OutFileBranches:
  - TauClassifier_Labels
  - TauJets_truthDecayMode
  - TauJets_truthProng
  - TauClassifier_pTReweight
  - TauJets_mu
  - TauJets_ptJetSeed
  - TauJets_etaJetSeed
  - TauJets_phiJetSeed
  - TauJets_RNNJetScoreSigTrans
  - TauJets_is1p0n
  - TauJets_is1p1n
  - TauJets_is1pXn
  - TauJets_is3p0n
  - TauJets_is3pXn
  - TauJets_mcEventWeight