---
# @package _group_
# Test/Train/Val split params
TestSplit: 0.2
ValSplit: 0.2
RandomSeed: 42

# Configure post-training actions
save_ntuples: True
make_plots: True

# Training config params
learning_rate: 1e-4
batch_size: 526
val_batch_size: 100000
epochs: 200
is_sparse: True
alpha: [0.1, 0.1, 0.15, 0.2, 0.2, 0.25]
gamma: 2 # [1, 2, 3, 3, 2.5, 3]

# Callbacks
callbacks:
  # Learining rate schedd
  lr_schedd:
    enabled: True
    factor: 0.75
    patience: 3
    min_lr: 1e-9

  # Early stopping
  early_stopping:
    enabled: True
    min_delta: 0.0001
    patience: 5

  # Model checkpoint
  model_checkpoint:
    enabled: True

  # Tensorboard callback
  tensorboard:
    enabled: True
  
  # Simple logging
  logging:
    enabled: True
  
  # Confusion matrix tensorboard callback
  # Note: This seems to be quite slow so is disabled by default
  conf_matrix:
    enabled: False